[project]
name = "math-verification"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "math-verify>=0.9.0",
    "vllm>=0.15.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
